"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, Recommendation } from "@/lib/api";

type Mode="ai"|"google";
type SearchResult={title:string;url:string;snippet?:string;provider?:string};
type DiscoveryItem={id:number;media_type:string;title:string;description?:string;genres?:string;release_year?:number|null;image_url?:string;imdb_rating?:number|null;public_rating?:number|null;runtime?:string;ott_india?:string;seasons?:number|null;episodes?:number|null;episode_duration?:string;languages?:string;watch_url?:string;source_url?:string;source?:string;trailer_url?:string};
type DiscoveryResult={item:DiscoveryItem;score:number;reasons:string[];source?:string};
type ChatResult={answer?:string;facts?:string[]};
const CATEGORIES=[{id:"all",label:"All",icon:"⌕"},{id:"movie",label:"Movies",icon:"🎬"},{id:"anime",label:"Anime",icon:"✦"},{id:"tv",label:"TV Shows",icon:"▣"},{id:"game",label:"Games",icon:"◉"},{id:"book",label:"Books",icon:"▰"},{id:"video",label:"Videos",icon:"▶"},{id:"news",label:"News",icon:"⌁"},{id:"website",label:"Websites",icon:"↗"}] as const;
const mediaWords:Record<string,string[]>={movie:["movie","movies","film","films","cinema"],anime:["anime","manga"],tv:["tv","show","shows","series","season","episode"],game:["game","games","gaming","steam","xbox","playstation"],book:["book","books","novel","novels","reading"]};
function infer(q:string){const words=q.toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/);for(const [type,keys] of Object.entries(mediaWords))if(keys.some(k=>words.includes(k)))return type;return "all"}
function googleUrl(q:string,cat:string){const extra=cat==="movie"?" movies":cat==="anime"?" anime":cat==="tv"?" TV series":cat==="game"?" video games":cat==="book"?" books":cat==="video"?" videos":cat==="news"?" news":"";return `https://www.google.com/search?q=${encodeURIComponent(q+extra)}`}

export default function SearchExperience(){
 const[mode,setMode]=useState<Mode>("ai"),[category,setCategory]=useState("all"),[query,setQuery]=useState(""),[results,setResults]=useState<SearchResult[]>([]),[discovery,setDiscovery]=useState<DiscoveryResult[]>([]),[answer,setAnswer]=useState<ChatResult|null>(null),[localRecs,setLocalRecs]=useState<Recommendation[]>([]),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false),[error,setError]=useState("");
 useEffect(()=>{api<Recommendation[]>("/recommendations?limit=12").then(setLocalRecs).catch(()=>setLocalRecs([]))},[]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.querySelector<HTMLInputElement>(".global-search input")?.focus()}};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[]);
 async function runSearch(e?:FormEvent){e?.preventDefault();const text=query.trim();if(!text||busy)return;const inferred=category==="all"?infer(text):category;setCategory(inferred);setSearched(true);setBusy(true);setError("");setAnswer(null);setResults([]);setDiscovery([]);
   if(mode==="google")window.open(googleUrl(text,inferred),"_blank","noopener,noreferrer");
   try{
     if(["movie","anime","tv","game","book"].includes(inferred)){const p=new URLSearchParams({media_type:inferred,limit:"18",query:text});const d=await api<DiscoveryResult[]>(`/discover?${p}`);setDiscovery(d||[])}
     let web:{results:SearchResult[]}={results:[]};try{web=await api<{results:SearchResult[]}>(`/research/search`,{method:"POST",body:JSON.stringify({query:text})});setResults(web.results||[])}catch(err){if(mode==="ai")throw err;setError("Google was opened for the full web. Structured media results are shown here when available.")}
     if(mode==="ai"&&inferred==="all"&&web.results?.length){const evidence=web.results.slice(0,8).map((r,i)=>`${i+1}. ${r.title}\n${r.snippet||""}\n${r.url}`).join("\n\n");const a=await api<ChatResult>("/chat",{method:"POST",body:JSON.stringify({message:`Answer this query using the fresh public web evidence below. Do not invent facts. Query: ${text}\n\n${evidence}`})});setAnswer(a)}
   }catch(err){setError(err instanceof Error?err.message:"Search failed")}finally{setBusy(false)}
 }
 const quick=(q:string,c:string)=>{setQuery(q);setCategory(c);setTimeout(()=>void runSearch(),0)};const catLabel=CATEGORIES.find(c=>c.id===category)?.label||"All";
 return <section className="search-experience" aria-label="Manu AI search"><div className="search-topbar"><div className="search-brand"><span>M</span><strong>Manu</strong><b>AI</b></div><div className="search-top-actions"><button onClick={()=>setMode("google")} className={mode==="google"?"active":""}>Google</button><button onClick={()=>setMode("ai")} className={mode==="ai"?"active":""}>AI</button><div className="search-avatar">M</div></div></div>
 <main className="search-hero"><div className="search-kicker">PERSONAL SEARCH & DISCOVERY</div><h1>Manu<span>AI</span></h1><p>Search the web, discover media, and use your personal taste — from one box.</p><form className="global-search" onSubmit={runSearch}><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything…" aria-label="Search anything" autoFocus/><div className="mode-toggle"><button type="button" className={mode==="ai"?"active":""} onClick={()=>setMode("ai")}>✦ AI Search</button><i/><button type="button" className={mode==="google"?"active":""} onClick={()=>setMode("google")}>G Google</button></div><button className="global-submit" type="submit" disabled={busy}>{busy?"…":"→"}</button></form><div className="category-strip">{CATEGORIES.map(c=><button key={c.id} type="button" className={category===c.id?"active":""} onClick={()=>setCategory(c.id)}>{c.icon} {c.label}</button>)}</div><div className="search-hint">⌘ K to focus · choose a type for personalized cards</div></main>
 {error&&<div className="search-error">{error}</div>}
 {!searched?<div className="discovery-content">{localRecs.length>0&&<section className="taste-section"><div className="results-title"><div><span>YOUR TASTE</span><h2>Recommended for you</h2></div><button onClick={()=>quick("movies I should watch","movie")}>Explore movies →</button></div><div className="recommendation-grid-search">{localRecs.slice(0,6).map(r=><article className="taste-card" key={r.item.id}><div className="taste-poster">{r.item.image_url&&<img src={r.item.image_url} alt=""/>}</div><div className="taste-copy"><span className="match">{r.score}% <em>match</em></span><h3>{r.item.title}</h3><p>{r.item.genres||"Personal pick"}</p><small>{r.reasons?.[0]}</small></div></article>)}</div></section>}</div>:<div className="search-content">
 {answer&&mode==="ai"&&<article className="search-ai-answer"><div className="answer-label">MANU AI · WEB-AUGMENTED</div><p>{answer.answer}</p>{answer.facts?.length?<div className="answer-facts">{answer.facts.slice(0,5).map(f=><span key={f}>✓ {f}</span>)}</div>:null}</article>}
 {discovery.length>0&&<section className="discovery-results"><div className="results-title"><div><span>PERSONALIZED {catLabel.toUpperCase()}</span><h2>{catLabel} matches for “{query}”</h2></div><div className="result-actions"><span>{discovery.length} cards</span><button onClick={()=>window.open(googleUrl(query,category),"_blank","noopener,noreferrer")}>Google ↗</button></div></div><div className="media-discovery-grid">{discovery.map(r=><DiscoveryCard key={`${r.item.id}-${r.item.title}`} result={r}/>)}</div></section>}
 <section className="web-results-block"><div className="results-title"><div><span>WEB RESULTS</span><h2>{results.length?`Results for “${query}”`:mode==="google"?"Google search opened":"No web results"}</h2></div>{mode==="google"&&<button onClick={()=>window.open(googleUrl(query,category),"_blank","noopener,noreferrer")}>Open Google ↗</button>}</div>{results.map(r=><a className="search-result-card" key={`${r.url}-${r.title}`} href={r.url} target="_blank" rel="noreferrer"><small>{(()=>{try{return new URL(r.url).hostname}catch{return r.url}})()}</small><h3>{r.title}</h3><p>{r.snippet||"Open result"}</p></a>)}{!results.length&&!discovery.length&&mode!=="google"&&<div className="no-results-card">No public results returned. Configure a web-search provider in your local environment or use Google.</div>}</section></div>}
 <footer className="search-footer"><span>Private library stays local</span><span>Web search on demand</span><span>AI uses fresh public evidence</span></footer></section>
}

function DiscoveryCard({result}:{result:DiscoveryResult}){const i=result.item;const series=i.media_type==="tv"||i.media_type==="anime";return <article className="discovery-card"><div className="discovery-poster">{i.image_url?<img src={i.image_url} alt={`${i.title} poster`}/>:<strong>{i.title.slice(0,1)}</strong>}<b>{result.score}% match</b></div><div className="discovery-card-body"><div className="card-title-row"><div><h3>{i.title}</h3><p>{i.release_year||"—"} · {i.genres||i.media_type}</p></div>{i.imdb_rating?<strong className="imdb">IMDb {i.imdb_rating}</strong>:null}</div><p className="card-description">{i.description||"No synopsis available."}</p><div className="meta-pills">{i.public_rating?<span>★ {i.public_rating}</span>:null}{i.runtime?<span>⏱ {i.runtime}</span>:null}{i.ott_india?<span>▣ {i.ott_india}</span>:null}{series&&i.seasons?<span>▤ {i.seasons} seasons</span>:null}{series&&i.episodes?<span>• {i.episodes} episodes</span>:null}{series&&i.episode_duration?<span>⌛ {i.episode_duration}</span>:null}</div>{i.languages&&<p className="language-line">🌐 <strong>Languages:</strong> {i.languages}</p>}<p className="fit-reason">✦ {result.reasons?.[0]||"Matches your saved taste."}</p><div className="discovery-actions">{i.watch_url&&<a className="watch-button" href={i.watch_url} target="_blank" rel="noreferrer">▶ Where to watch ↗</a>}{i.trailer_url&&<a className="details-button" href={i.trailer_url} target="_blank" rel="noreferrer">Trailer ↗</a>}{i.source_url&&<a className="details-button" href={i.source_url} target="_blank" rel="noreferrer">Details ↗</a>}</div><div className="source-line">{i.source||"public"} · metadata checked live</div></div></article>}
