"use client";
import { useEffect, useState } from "react";
import SearchExperience from "@/components/search-experience";
import { Sidebar } from "@/components/sidebar";
import { MediaCard } from "@/components/media-card";
import { api, MediaItem, Memory, Recommendation } from "@/lib/api";

const labels: Record<string,string> = { home:"Home", discover:"Discover", movie:"Movies", anime:"Anime", tv:"TV Shows", game:"Games", book:"Books", memory:"Memory", data:"Data", ai:"AI", settings:"Settings" };
const mediaTypes: Record<string,string> = { movie:"movie", anime:"anime", tv:"tv", game:"game", book:"book" };
type Summary={database_bytes:number;counts:Record<string,number>;memories:number;last_backup:string|null;backup_location:string};

export default function Dashboard(){
 const [page,setPage]=useState("home"),[items,setItems]=useState<MediaItem[]>([]),[recs,setRecs]=useState<Recommendation[]>([]),[memories,setMemories]=useState<Memory[]>([]),[summary,setSummary]=useState<Summary|null>(null),[loading,setLoading]=useState(true);
 const refresh=async()=>{try{const [m,r,mm,s]=await Promise.all([api<MediaItem[]>("/media"),api<Recommendation[]>("/recommendations?limit=24"),api<Memory[]>("/memories"),api<Summary>("/data/summary")]);setItems(m);setRecs(r);setMemories(mm);setSummary(s)}catch{}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[]);
 if(loading)return <div className="boot"><span className="brand-mark">M</span><p>Opening Manu AI…</p></div>;
 const label=labels[page]||"Home";
 return <main className="shell"><Sidebar active={page} onNavigate={setPage}/><section className="main"><header className="topbar"><div className="crumb">Manu AI <span>/</span> {label}</div><div className="top-actions"><div className="avatar">M</div></div></header>{page==="home"&&<SearchExperience/>}{page==="discover"&&<Discover recs={recs}/>} {mediaTypes[page]&&<Library label={label} items={items.filter(x=>x.media_type===mediaTypes[page])}/>} {page==="memory"&&<MemoryPage memories={memories} refresh={refresh}/>} {page==="data"&&<DataPage summary={summary}/>} {page==="ai"&&<AIPage/>} {page==="settings"&&<Settings/>}</section></main>;
}

function Discover({recs}:{recs:Recommendation[]}){return <div className="content"><section className="page-intro"><p className="eyebrow">DISCOVER</p><h1>Find your next obsession.</h1><p>Personalized recommendations from your saved taste and catalogue.</p></section>{recs.length?<div className="recommendation-grid">{recs.map(r=><MediaCard key={r.item.id} recommendation={r}/>)}</div>:<div className="library-empty"><h2>No recommendations yet.</h2><p>Use Home search to discover current movies, anime, shows, games and books.</p></div>}</div>}

function Library({label,items}:{label:string;items:MediaItem[]}){const[q,setQ]=useState("");const show=items.filter(i=>i.title.toLowerCase().includes(q.toLowerCase()));return <div className="content"><section className="library-head"><div><p className="eyebrow">YOUR LIBRARY</p><h1>{label}</h1><p>{items.length} {items.length===1?"item":"items"} saved locally.</p></div></section><div className="library-tools"><div className="search-field"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${label.toLowerCase()}…`}/></div></div>{show.length?<div className="library-grid">{show.map(i=><MediaCard key={i.id} item={i}/>)}</div>:<div className="library-empty"><h2>No saved {label.toLowerCase()}.</h2><p>Your local library can be empty. Home still searches the internet and can personalize discovery.</p></div>}</div>}

function MemoryPage({memories,refresh}:{memories:Memory[];refresh:()=>void}){const[text,setText]=useState("");const[category,setCategory]=useState("favorite genres");async function add(e:React.FormEvent){e.preventDefault();if(!text.trim())return;await api("/memories",{method:"POST",body:JSON.stringify({category,content:text,source:"user"})});setText("");refresh()}return <div className="content"><section className="page-intro narrow"><p className="eyebrow">MEMORY</p><h1>Your taste profile.</h1><p>Preferences here influence personalized ranking.</p></section><section className="panel memory-add"><form onSubmit={add}><select value={category} onChange={e=>setCategory(e.target.value)}><option>favorite genres</option><option>disliked genres</option><option>preferred pacing</option><option>preferred runtime</option><option>favorite themes</option><option>things to avoid</option></select><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a preference…"/><button className="primary-button">Save</button></form></section><div className="memory-cards">{memories.map(m=><article className="memory-card" key={m.id}><div><span>{m.category}</span><p>{m.content}</p></div><button className="danger-button" onClick={async()=>{await api(`/memories/${m.id}`,{method:"DELETE"});refresh()}}>Delete</button></article>)}</div></div>}

function DataPage({summary}:{summary:Summary|null}){const total=summary?Object.values(summary.counts).reduce((a,b)=>a+b,0):0;return <div className="content"><section className="page-intro narrow"><p className="eyebrow">DATA</p><h1>Your data.</h1><p>Your library and memory remain local to this application.</p></section><div className="data-overview panel"><div><span>Stories</span><b>{total}</b></div><div><span>Memories</span><b>{summary?.memories||0}</b></div><div><span>Database</span><b>{summary?`${Math.round(summary.database_bytes/1024)} KB`:"—"}</b></div></div></div>}

function AIPage(){const[q,setQ]=useState("");const[answer,setAnswer]=useState("");const[busy,setBusy]=useState(false);async function ask(e:React.FormEvent){e.preventDefault();if(!q.trim())return;setBusy(true);try{const r=await api<{answer?:string}>("/chat",{method:"POST",body:JSON.stringify({message:q})});setAnswer(r.answer||"")}catch{}finally{setBusy(false)}}return <div className="content ai-page"><section className="page-intro narrow"><p className="eyebrow">MANU AI</p><h1>Ask anything.</h1><p>Dedicated assistant mode. Normal web and media search stays on Home.</p></section><div className="chat-shell">{answer&&<article className="ai-answer"><span className="ai-label">MANU AI</span><p>{answer}</p></article>}<form className="chat-input" onSubmit={ask}><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask Manu AI…" rows={3}/><button className="primary-button" disabled={busy}>{busy?"Thinking…":"Ask Manu →"}</button></form></div></div>}

function Settings(){return <div className="content"><section className="page-intro narrow"><p className="eyebrow">SETTINGS</p><h1>Make Manu yours.</h1><p>Search and personalization behavior.</p></section><div className="settings-list"><article className="setting-row"><div><h3>Single-box search</h3><p>AI Search and Google/Web Search share one query. Switching modes never redirects.</p></div><span className="status-pill">Active</span></article><article className="setting-row"><div><h3>Personalized media cards</h3><p>Cards use stored preferences and real catalogue metadata; missing fields are never invented.</p></div><span className="status-pill">Active</span></article><article className="setting-row"><div><h3>Internet access</h3><p>Web search is on demand and provider credentials are kept in your local environment.</p></div><span className="status-pill">On demand</span></article></div></div>}
