"use client";
import { useEffect, useState } from "react";
import { API_URL } from "@/lib/api";

type Memory={id:number;category:string;content:string;source:string;confidence:number|null};
type Snapshot={generated_at:string;explicit_memories:Memory[];inferred_memories:Memory[];library:any[];watchlist:any[];instructions_for_chatgpt:string};

export default function MemoryBridge(){
 const [text,setText]=useState(""); const [memories,setMemories]=useState<Memory[]>([]); const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
 const load=async()=>{try{const [m,s]=await Promise.all([fetch(`${API_URL}/memories`),fetch(`${API_URL}/memories/snapshot`)]);setMemories(await m.json());setSnapshot(await s.json())}catch{setStatus("Start Manu AI first with ./start.sh")}};
 useEffect(()=>{load()},[]);
 const importText=async()=>{if(!text.trim())return;setBusy(true);setStatus("");try{const r=await fetch(`${API_URL}/memories/import`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw new Error((await r.json()).detail||"Import failed");const x=await r.json();setStatus(x.summary);setText("");await load()}catch(e){setStatus(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}};
 const copy=async()=>{if(!snapshot)return;const payload={MANU_AI_HANDOFF_VERSION:"1.0",instructions:snapshot.instructions_for_chatgpt,explicit_memory:snapshot.explicit_memories,inferred_memory:snapshot.inferred_memories,raw_library:snapshot.library,watchlist:snapshot.watchlist};await navigator.clipboard.writeText(JSON.stringify(payload,null,2));setStatus("Full Manu AI snapshot copied. Paste it into ChatGPT when you want me to understand the current local state.")};
 return <main className="bridge-page"><div className="bridge-orb"/><header><a href="/">← Manu AI</a><span className="status-dot">● Local bridge</span></header><section className="bridge-hero"><p className="eyebrow">CHATGPT ↔ MANU AI</p><h1>Teach your local AI.<br/><em>Keep the memory yours.</em></h1><p>Paste anything from ChatGPT here. Manu AI turns the raw text into clean, searchable memory signals. Nothing is uploaded to a cloud service by this page.</p></section><section className="bridge-grid"><article className="bridge-card import-card"><div className="card-kicker">01 · FEED MANU</div><h2>Paste context from ChatGPT</h2><p>Paste a conversation excerpt, a preference, a project decision, or anything you explicitly want your local AI to remember.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste ChatGPT context here…\n\nExample:\nI watched Shutter Island and loved the mystery and twist. I prefer shorter, intense stories with strong endings."/><button className="bridge-button" onClick={importText} disabled={busy}>{busy?"Optimising…":"✦ Optimise & feed to Manu AI"}</button>{status&&<div className="bridge-status">{status}</div>}</article><article className="bridge-card export-card"><div className="card-kicker">02 · SHOW CHATGPT</div><h2>One-click full snapshot</h2><p>Generate a clean handoff containing your explicit memory, AI-inferred memory, raw library data, and watchlist.</p><div className="snapshot-stats"><b>{memories.length}</b><span>memory signals</span><b>{snapshot?.library.length||0}</b><span>raw library items</span></div><button className="bridge-button secondary" onClick={copy} disabled={!snapshot}>⤴ Copy everything for ChatGPT</button><small>This copies the snapshot to your clipboard. You choose where to paste it.</small></article></section><section className="how"><div><span>01</span><h3>Paste</h3><p>Bring useful context from this ChatGPT conversation.</p></div><div><span>02</span><h3>Optimise</h3><p>Manu AI stores it as explicit, labelled memory rather than one giant blob.</p></div><div><span>03</span><h3>Share</h3><p>Copy the current state back here whenever you want ChatGPT to understand Manu AI.</p></div></section><footer>Private by design · Explicit memory and inferred memory stay visibly separated</footer></main>
}
