"use client";
import { useEffect, useState } from "react";
import { API_URL } from "@/lib/api";

type Memory={id:number;category:string;content:string;source:string;confidence:number|null};
type Snapshot={generated_at:string;explicit_memories:Memory[];inferred_memories:Memory[];library:any[];watchlist:any[];instructions_for_chatgpt:string};

export default function MemoryBridge(){
 const [text,setText]=useState(""); const [memories,setMemories]=useState<Memory[]>([]); const [snapshot,setSnapshot]=useState<Snapshot|null>(null); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false); const [proposals,setProposals]=useState<any[]>([]);
 const load=async()=>{try{const [m,s]=await Promise.all([fetch(`${API_URL}/memories`),fetch(`${API_URL}/memories/snapshot`)]);setMemories(await m.json());setSnapshot(await s.json())}catch{setStatus("Start Manu AI first with ./start.sh")}};
 useEffect(()=>{load()},[]);
 const curate=async()=>{if(!text.trim())return;setBusy(true);setStatus("");try{const r=await fetch(`${API_URL}/memories/curate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw new Error((await r.json()).detail||"Curation failed");const x=await r.json();setProposals(x.proposals||[]);setStatus(`Found ${x.proposals?.length||0} memory proposals. Review them before saving.`)}catch(e){setStatus(e instanceof Error?e.message:"Curation failed")}finally{setBusy(false)}};
 const save=async(p:any)=>{await fetch(`${API_URL}/memories`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:p.category,content:p.content,source:"inferred",confidence:p.confidence,is_demo:false})});setProposals(v=>v.filter(x=>x!==p));await load();setStatus("Approved memory saved locally.")};
 const saveAll=async()=>{for(const p of proposals)await save(p)};
 const copy=async()=>{if(!snapshot)return;const payload={MANU_AI_HANDOFF_VERSION:"1.1",instructions:snapshot.instructions_for_chatgpt,explicit_memory:snapshot.explicit_memories,inferred_memory:snapshot.inferred_memories,raw_library:snapshot.library,watchlist:snapshot.watchlist};await navigator.clipboard.writeText(JSON.stringify(payload,null,2));setStatus("Full Manu AI snapshot copied. Paste it into ChatGPT.")};
 return <main className="bridge-page"><div className="bridge-orb"/><header><a href="/">← Manu AI</a><span className="status-dot">● Local bridge</span></header><section className="bridge-hero"><p className="eyebrow">CHATGPT ↔ MANU AI</p><h1>Teach your local AI.<br/><em>Keep the memory yours.</em></h1><p>Paste anything from ChatGPT. Manu AI analyses it locally and proposes clean memories. You decide what becomes permanent.</p></section><section className="bridge-grid"><article className="bridge-card import-card"><div className="card-kicker">01 · MEMORY LAB</div><h2>Paste context from ChatGPT</h2><p>Paste a conversation excerpt, preference, project decision, or anything you want Manu AI to understand.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste ChatGPT context here…"/><button className="bridge-button" onClick={curate} disabled={busy}>{busy?"Analysing locally…":"✦ Analyse & optimise"}</button>{status&&<div className="bridge-status">{status}</div>}{proposals.length>0&&<div className="proposals"><div className="proposal-head"><b>Memory proposals</b><button onClick={saveAll}>Approve all</button></div>{proposals.map((p,i)=><article className="proposal" key={i}><div><span>{p.category}</span><strong>{Math.round((p.confidence||0)*100)}% confidence</strong></div><p>{p.content}</p><small>Why: {p.reason}</small><div><button onClick={()=>save(p)}>Approve</button><button onClick={()=>setProposals(v=>v.filter(x=>x!==p))}>Reject</button></div></article>)}</div>}</article><article className="bridge-card export-card"><div className="card-kicker">02 · SHOW CHATGPT</div><h2>One-click full snapshot</h2><p>Generate a handoff containing explicit memory, inferred memory, raw library data, and watchlist.</p><div className="snapshot-stats"><b>{memories.length}</b><span>memory signals</span><b>{snapshot?.library.length||0}</b><span>raw library items</span></div><button className="bridge-button secondary" onClick={copy} disabled={!snapshot}>⤴ Copy everything for ChatGPT</button><small>This stays on your clipboard until you paste it somewhere.</small></article></section><section className="how"><div><span>01</span><h3>Paste</h3><p>Bring useful context from ChatGPT.</p></div><div><span>02</span><h3>Review</h3><p>Ollama proposes memories with confidence and reasons.</p></div><div><span>03</span><h3>Approve</h3><p>Only approved memories enter your local profile.</p></div></section><footer>Private by design · Local-first · Explicit and inferred memory stay separated</footer></main>
}
