"use client";
import { useEffect, useState } from "react";
import { API_URL } from "@/lib/api";
import "./discovery.css";

type Candidate={item:{id:number;title:string;media_type:string;genres:string;description:string;image_url:string;imdb_rating:number|null;runtime:string;ott_india:string;intensity:string;ending_type:string;release_year:number|null};score:number;reasons:string[];source:string};
type WebResult={title:string;url:string;snippet:string;provider:string};

export default function DiscoveryPage(){
 const [items,setItems]=useState<Candidate[]>([]),[query,setQuery]=useState(""),[web,setWeb]=useState<WebResult[]>([]),[busy,setBusy]=useState(true),[searching,setSearching]=useState(false),[error,setError]=useState("");
 const load=async()=>{setBusy(true);try{const r=await fetch(`${API_URL}/discover?limit=18`);if(!r.ok)throw new Error("Discovery API unavailable");setItems(await r.json());}catch(e){setError(e instanceof Error?e.message:"Could not load discovery")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const search=async(e:React.FormEvent)=>{e.preventDefault();if(!query.trim())return;setSearching(true);setError("");try{const [local,online]=await Promise.all([fetch(`${API_URL}/discover?query=${encodeURIComponent(query)}&limit=18`),fetch(`${API_URL}/discover/web?query=${encodeURIComponent(query)}&limit=8`)]);if(!local.ok||!online.ok)throw new Error("Live research failed");setItems(await local.json());setWeb((await online.json()).results||[])}catch(err){setError(err instanceof Error?err.message:"Live research failed")}finally{setSearching(false)}};
 return <main className="discovery-shell"><div className="discovery-noise"/><header><div className="wordmark"><span>✦</span> MANU <i>AI</i></div><div className="status"><b/> LOCAL BRAIN <span>·</span> LIVE WEB</div></header><section className="discovery-hero"><p className="kicker">PERSONAL DISCOVERY INTELLIGENCE</p><h1>Don't search.<br/><em>Discover.</em></h1><p>Ollama thinks with your private taste. The web supplies what is new. Manu AI decides what deserves your attention.</p><form onSubmit={search}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything — movies, anime, games, books…"/><button>{searching?"Researching…":"Explore"}</button></form>{error&&<small className="error">{error}</small>}</section>
 <section className="signal"><div><b>{busy?"—":items.length}</b><span>PERSONAL MATCHES</span></div><div><b>{web.length||"∞"}</b><span>LIVE WEB SIGNALS</span></div><div><b>QWEN</b><span>LOCAL REASONING</span></div></section>
 <section className="results"><div className="section-top"><div><p className="kicker">THE RANKING ENGINE</p><h2>Picked for <em>you.</em></h2></div><span>fit score ≠ rating · it is personal relevance</span></div>{busy?<div className="skeleton-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:<div className="cards">{items.map((c,i)=><article className="discover-card" key={c.item.id}><div className="poster" style={{backgroundImage:c.item.image_url?`url(${c.item.image_url})`:undefined}}><span>{String(i+1).padStart(2,"0")}</span><b>{c.score}% fit</b></div><div className="card-body"><div className="meta">{c.item.media_type} · {c.item.release_year||"new"} {c.item.imdb_rating?`· IMDb ${c.item.imdb_rating}`:""}</div><h3>{c.item.title}</h3><p>{c.item.genres}</p><div className="why">✦ {c.reasons[0]}</div><div className="chips">{c.item.runtime&&<span>{c.item.runtime}</span>}{c.item.intensity&&<span>{c.item.intensity}</span>}{c.item.ott_india&&<span>{c.item.ott_india}</span>}</div></div></article>)}</div>}</section>
 {web.length>0&&<section className="web-section"><div><p className="kicker">LIVE RESEARCH</p><h2>The internet is <em>listening.</em></h2><p>These are public sources found for your current search. They are not treated as personal facts.</p></div><div className="web-list">{web.map((r,i)=><a href={r.url} target="_blank" rel="noreferrer" key={r.url}><span>0{i+1}</span><div><b>{r.title}</b><small>{r.snippet}</small></div><strong>↗</strong></a>)}</div></section>}
 <footer>PRIVATE MEMORY STAYS LOCAL <span>◆</span> PUBLIC RESEARCH IS READ-ONLY</footer></main>
}
